name: Deploy Components to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Pull Components and Rebuild App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            # 1. Update the MAIN App (incase there are other changes)
            cd /home/wayne/web/admin.connexbiz.com/public_html
            # (Optional) git pull origin main 
            
            # 2. Update the Shared Components (Force Clean)
            cd app/_components
            git reset --hard origin/main
            git pull origin main
            
            # 3. Go back to Root and Rebuild
            cd ../..
            npm install
            npm run build
            pm2 reload ecosystem.config.js --env production
